[package]
name = "tera-cli"
version = "0.0.1-a0"
edition = "2021"

[[bin]]
name = "tera"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
anyhow = "1.0"
tera = {version = "1", default-features = false}
