[package]
name = "tera-cli"
version = "0.0.1-a4"
edition = "2021"

[[bin]]
name = "tera"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.81"
clap = { version = "4.5.4", features = ["derive"] }
env_logger = "0.11.3"
log = "0.4.21"
notify = "6.1.1"
tera = "1.19.1"
