name: CI

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Audit dependencies
        run: cargo audit
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Lint with clippy
        run: cargo clippy -- -D warnings
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.1
      - name: Run pre-commit hooks
        run: pre-commit run -a
